version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -l
            DEBIAN_FRONTEND=noninteractive
            apt-get -y update
            apt-get -y install nodejs
            npm install
            npm test
            