version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run:
          name: Install packages
          command:
            npm install
      - run:
          name: Run test
          command: 
            npm test
            