version: 2.0
jobs:
  build:
    docker:
      - image: rrstowell/dealer:latest
        auth: 
          username: rrstowell
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install packages
          command:
            npm install
      - run:
          name: Run test
          command: 
            npm test
            